name: Deploy DigitalMarketing App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy DigitalMarketing to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@13.124.245.114 << 'EOF'
            cd ~/landingpage-test/Marketti.ae/DigitalMarketing || {
              mkdir -p ~/landingpage-test/Marketti.ae
              cd ~/landingpage-test/Marketti.ae
              git clone https://github.com/Traptishukla/landingpage-test.git temp
              mv temp/DigitalMarketing ./DigitalMarketing
              rm -rf temp
            }
            cd ~/landingpage-test/Marketti.ae/DigitalMarketing
            sudo git pull origin main
            sudo npm install
            sudo npm run build
            pm2 restart digitalmarketing || pm2 start npm --name digitalmarketing -- start
          EOF
