name: Deploy LinkedIn to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy LinkedIn project to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/landingpage-test/Marketti.ae/LinkedIn
          git pull origin main
          npm install
          npm run build
          pm2 restart linkedin || PORT=3001 pm2 start npm --name "linkedin" -- start
        EOF
