name: Deploy LinkedIn to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy LinkedIn project to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} "
          cd /home/ubuntu/landingpage-test/Marketti.ae/LinkedIn &&
          sudo chown -R ubuntu:ubuntu . &&
          rm -rf node_modules package-lock.json &&
          npm install &&
          npx next build &&
          pm2 restart linkedin || PORT=3001 pm2 start npm --name "linkedin" -- start
        "
