name: Deploy LinkedIn App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy LinkedIn App (port 4000)
      env:
        HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -tt -o StrictHostKeyChecking=no -i key.pem ubuntu@$HOST << 'EOF'
          cd /home/ubuntu/landingpage-test/Marketti.ae/LinkedIn
          git pull origin main
          sudo chown -R ubuntu:ubuntu .
          rm -rf node_modules package-lock.json
          npm install
          npm run build
          pm2 restart linkedin || pm2 start npm --name "linkedin" -- start -- -p 4000
        EOF
