name: Deploy Next.js to EC2 server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2 and Restart App
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} <<EOF
          cd /home/ubuntu/landingpage-test/Marketti.ae/DigitalMarketing

          # Set Git credentials with token
          git config --global credential.helper store
          echo "https://${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

          git pull https://${{ secrets.GH_TOKEN }}@github.com/Traptishukla/landingpage-test.git main

          sudo npm install
          sudo npm run build
          pm2 restart digitalmarketing || pm2 start npm --name "digitalmarketing" -- start
        EOF
