name: Deploy Next.js to EC2 server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2 and Restart App
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} "
          cd /home/ubuntu/landingpage-test/Marketti.ae/DigitalMarketing &&
          sudo chown -R ubuntu:ubuntu . &&
          rm -rf node_modules package-lock.json &&
          npm install &&
          npx next build &&
          pm2 restart digitalmarketing || pm2 start npm --name 'digitalmarketing' -- start
        "


