name: Deploy Next.js to EC2 server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2 and Restart App
      run: |
        ssh -tt -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/landingpage-test/Marketti.ae/DigitalMarketing

          echo "Pulling latest code from main branch..."
          git pull origin main

          echo "Installing dependencies..."
          npm install

          echo "Building app..."
          npm run build

          echo "Restarting PM2 app..."
          pm2 restart digitalmarketing || pm2 start npm --name "digitalmarketing" -- start

          echo "✅ Deployment complete"
          sleep 2
        EOF
